--liquibase formatted sql

--changeset viktor-vv:20240715-1 failOnError:true
--comment: Create metrics table.
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'metrics';
create table if not exists metrics
(
    id          BIGINT generated by default as identity PRIMARY KEY,
    name        VARCHAR NOT NULL,
    data        VARCHAR NOT NULL,
    description VARCHAR
);