openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /send:
    post:
      tags:
        - Система отправки метрик
      summary: 'Отправка метрик'
      operationId: sendMetrics
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Metric'
components:
  schemas:
    Metric:
      required:
        - data
        - name
      type: object
      properties:
        name:
          type: string
        data:
          type: string
        description:
          type: string
